#+TITLE: MY DOOM EMACS
#+AUTHOR: Swapnil Mahajan (swapnilsm@)
#+STARTUP: SHOWEVERYTHING
#+OPTIONS: TOC:2
#+PROPERTY: header-args:elisp

* TABLE OF CONTENTS                                                                                                :TOC:
- [[#help][HELP]]
- [[#enable-lexical-binding][ENABLE LEXICAL BINDING]]
- [[#identity][IDENTITY]]
- [[#appearance][APPEARANCE]]
  - [[#font][FONT]]
  - [[#theme][THEME]]
  - [[#splash-image][SPLASH IMAGE]]
  - [[#titlebar---version-29][TITLEBAR - Version 29+]]
  - [[#other][OTHER]]
- [[#org][ORG]]
  - [[#org-directory][ORG DIRECTORY]]
  - [[#capture-templates][CAPTURE TEMPLATES]]
  - [[#preview][PREVIEW]]
  - [[#org-ql][ORG QL]]
  - [[#default-apps][DEFAULT APPS]]
  - [[#priorities][PRIORITIES]]
  - [[#agenda][AGENDA]]
  - [[#super-agenda][SUPER AGENDA]]
  - [[#agenda-property][AGENDA PROPERTY]]
  - [[#pomodoro][POMODORO]]
  - [[#auto-clockout][AUTO CLOCKOUT]]
  - [[#copy-link-at-point][COPY LINK AT POINT]]
  - [[#insert-current-org-timer][INSERT CURRENT ORG TIMER]]
  - [[#insert-current-date][INSERT CURRENT DATE]]
  - [[#insert-update][INSERT UPDATE]]
  - [[#google-calendar][GOOGLE CALENDAR]]
  - [[#org-pandoc-import][ORG PANDOC IMPORT]]
  - [[#presentation][PRESENTATION]]
  - [[#superstar][SUPERSTAR]]
- [[#expand-region][EXPAND REGION]]
- [[#beacon][BEACON]]
- [[#dimmer][DIMMER]]
- [[#auto-revert][AUTO REVERT]]
- [[#hacks][HACKS]]
- [[#leetcode][LEETCODE]]
- [[#python][PYTHON]]
- [[#command-log-mode][COMMAND LOG MODE]]
- [[#protobuf-mode][PROTOBUF MODE]]
- [[#org-roam][ORG ROAM]]
  - [[#org-roam-1][ORG ROAM]]
  - [[#org-roam-ui][ORG ROAM UI]]
- [[#undo-tree][UNDO TREE]]
- [[#vterm][VTERM]]
- [[#company][COMPANY]]
- [[#request][REQUEST]]
- [[#google][GOOGLE]]
  - [[#google3][GOOGLE3]]
  - [[#file-handling][FILE HANDLING]]
  - [[#reference-search-correction-and-completion][REFERENCE, SEARCH, CORRECTION AND COMPLETION]]
  - [[#fig][FIG]]
  - [[#build][BUILD]]
  - [[#imports-and-includes][IMPORTS AND INCLUDES]]
  - [[#coding-help-aka-snippets][CODING HELP AKA SNIPPETS]]
  - [[#enable-google3-autogen][ENABLE GOOGLE3 AUTOGEN]]
  - [[#language][LANGUAGE]]
  - [[#custom-code][CUSTOM CODE]]
  - [[#formatting][FORMATTING]]
  - [[#ediff][EDIFF]]
  - [[#links--documentation][LINKS & DOCUMENTATION]]
  - [[#buganizer][Buganizer]]
  - [[#custom-functions][CUSTOM FUNCTIONS]]
  - [[#hooks][HOOKS]]
  - [[#necessary-rather-than-using-doom-auto-revert-mode-to-enable-eglot-reconnect][NECESSARY RATHER THAN USING DOOM AUTO-REVERT MODE TO ENABLE EGLOT-RECONNECT.]]
  - [[#keymap][KEYMAP]]
  - [[#hacks-1][HACKS]]
  - [[#speed-up-file-opens][SPEED UP FILE OPENS]]
  - [[#expand-region-1][EXPAND REGION]]
  - [[#projectile][PROJECTILE]]
  - [[#datetimecalendar][DATE/TIME/CALENDAR]]
  - [[#test][Test]]

* HELP

Here are some additional functions/macros that could help you configure Doom:

- =load!= for loading external *.el files relative to this one
- =use-package!= for configuring packages
- =after!= for running code after a package has loaded
- =add-load-path!= for adding directories to the =load-path=, relative to
  this file. Emacs searches the =load-path= when you load packages with
  =require= or =use-package=.
- =map!= for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.

* ENABLE LEXICAL BINDING
This section needs to be the first SRC block so that the comment appears at
the top of the file generated.
#+BEGIN_SRC elisp
;; -*- lexical-binding: t; -*-
#+END_SRC

* IDENTITY
Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.
#+BEGIN_SRC elisp
(setq user-full-name "Swapnil Mahajan"
      user-mail-address "swapnilsm@google.com")
#+END_SRC

* APPEARANCE

** FONT
Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:

+ =doom-font=
+ =doom-variable-pitch-font=
+ =doom-big-font= -- used for =doom-big-font-mode=; use this for
  presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string. You generally only need these two:

#+BEGIN_SRC elisp
;; (setq doom-font (font-spec :family "Meslo LG L for Powerline" :size 15)
;;       doom-variable-pitch-font (font-spec :family "sans" :size 13))

;; (setq doom-font (font-spec :family "Monaco" :size 13))
;; (setq ns-use-thin-smoothing t)
;; (setq ns-antialias-text t)
;; (setq doom-font (font-spec :family "Iosevka Aile" :size 15 :weight 'light))
;; (setq doom-variable-pitch-font (font-spec :family "Iosevka Aile" :size 15 :weight 'regular))
;; (setq doom-font (font-spec :family "Fira Code" :size 15 :weight 'light))
;; (setq doom-variable-pitch-font (font-spec :family "Fira Code" :size 15 :weight 'light))
;; (setq doom-font (font-spec :family "Source Code Pro" :size 15 :weight 'light))
;; (setq doom-variable-pitch-font (font-spec :family "Source Code Pro" :size 15 :weight 'light))
;; (setq doom-font (font-spec :family "VictorMono Nerd Font Mono" :size 15 :weight 'regular))
;; (setq doom-variable-pitch-font (font-spec :family "VictorMono Nerd Font Mono" :size 15 :weight 'regular))
;; (setq doom-font (font-spec :family "FiraCode Nerd Font" :size 15 :weight 'regular))
;; (setq doom-variable-pitch-font (font-spec :family "FiraCode Nerd Font" :size 15 :weight 'regular))
(setq doom-font (font-spec :family "JetBrains Mono NL" :size 15 :weight 'regular))
(setq doom-variable-pitch-font (font-spec :family "JetBrains Mono NL" :size 15 :weight 'light))
;; (setq doom-variable-pitch-font (font-spec :family "Google Sans" :weight 'regular))
#+END_SRC

Use variable pitch font for text and fixed pitch font for code blocks
#+BEGIN_SRC elisp
(use-package! mixed-pitch
  :hook (text-mode . mixed-pitch-mode)
  :config
  (setq mixed-pitch-set-height t)
  (set-face-attribute 'variable-pitch nil :height 1.1))
#+END_SRC

** THEME
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set =doom-theme= or manually load a theme with the
=load-theme= function. This is the default:
#+BEGIN_SRC elisp
;; (setq doom-theme 'doom-monokai-spectrum)
;; (setq doom-theme 'doom-snazzy)
;; (setq doom-theme 'doom-dracula)
;; (setq doom-theme 'doom-old-hope)
(setq doom-theme 'doom-one)
#+END_SRC

** SPLASH IMAGE
Update the normal ASCII splash image on every startup
#+BEGIN_SRC elisp
(setq fancy-splash-image "~/dotfiles/.doom.d/pictures/iron-man-splash.png")
#+END_SRC

** TITLEBAR - Version 29+
Toggle title bar and rounded corners
#+BEGIN_SRC elisp
(add-to-list 'default-frame-alist '(undecorated-round . t))
#+END_SRC

** OTHER
This determines the style of line numbers in effect. If set to =nil=, line
numbers are disabled. For relative line numbers, set this to =relative=.
#+BEGIN_SRC elisp
(setq display-line-numbers-type 'relative)
#+END_SRC

Start Emacs in maximized mode
#+BEGIN_SRC elisp
(add-to-list 'initial-frame-alist '(fullscreen . maximized))
#+END_SRC

Ivy frame position
#+BEGIN_SRC elisp
;; (after! ivy-posframe
;;   (setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-frame-top-center))))
#+END_SRC

Truncate file name displayed in the modeline to truncate all except the project name & file name
#+BEGIN_SRC elisp
(setq doom-modeline-buffer-file-name-style 'truncate-except-project)
#+END_SRC

* ORG
** ORG DIRECTORY
If you use =org= and don't want your org files in the default location below,
change =org-directory=. It must be set before org loads!
#+BEGIN_SRC elisp
(use-package! org
  :init
  (setq org-directory "~/org-files/")
  (setq org-use-property-inheritance t)
  :commands (org-capture org-agenda)
  :config
  (message "Org mode loaded")
  ;; (org-clock-persistence-insinuate)
  ;; (setq org-clock-persist t
  ;;       org-clock-persist-query-resume nil
  ;;       org-clock-auto-clock-resolution 'when-no-clock-is-running
  ;;       org-clock-history-length 23
  ;;       org-clock-in-resume t)
  (setq org-tags-column -120))
#+END_SRC

** CAPTURE TEMPLATES
#+BEGIN_SRC elisp
(after! org
  (use-package! doct
    :config
    (setq org-capture-templates
          (doct '(("Todo" :keys "t"
                   :file "~/roam-files/20221104172849-todo.org"
                   :headline "Inbox"
                   :prepend t
                   :template ("* TODO %^{Description} [[%c][%?]]"))
                  ("Interview" :keys "i"
                   :file "~/roam-files/20210920135449-interviews.org"
                   :headline "Tasks"
                   :prepend t
                   :template ("* TODO Interview %^{Name}%? [[[%^{My gHire Link}][My gHire]]]"
                              "DEADLINE: %^{Date}t"))
                  ("Good read" :keys "r"
                   :file "~/roam-files/20220725134226-good_reads.org"
                   :headline "Good Reads"
                   :prepend t
                   :template ("* TODO [[%c][%^{Title}]]")))))))
#+END_SRC

** PREVIEW
#+BEGIN_SRC elisp
(after! org
  (use-package! ox-gfm))
#+END_SRC
** ORG QL
#+BEGIN_SRC elisp
(use-package! org-ql
  :after org)
#+END_SRC

** DEFAULT APPS
#+BEGIN_SRC elisp
(after! org
  (setq org-file-apps
        (append
         '(
           (auto-mode . emacs)
           (directory . emacs)
           ("\\.docx?\\'" . default)
           )
         org-file-apps))
  (setq grip-preview-use-webkit 'nil))
#+END_SRC

** PRIORITIES
*** Appearance
#+BEGIN_SRC elisp
(use-package! org-fancy-priorities
  :hook
  (org-mode . org-fancy-priorities-mode)
  :config
  (setq org-fancy-priorities-list '("[HIGH]" "[MID]" "[LOW]" "[OPT]")))
#+END_SRC

*** Inheritance
#+BEGIN_SRC elisp
(after! org
  (setq org-use-property-inheritance t))
#+END_SRC

** AGENDA
*** Load org-agenda
#+BEGIN_SRC elisp
(use-package! org-agenda
  :after org
  :commands org-agenda
  :config
  (setq org-refile-use-outline-path t)
  (setq org-refile-targets '((nil . (:tag . "TASKS"))
                             (org-agenda-files :tag . "TASKS")))
  (message "org-agenda loaded"))
#+END_SRC

#+RESULTS:
: t

*** Custom functions
**** Get property value: SHORT
#+BEGIN_SRC elisp
(defun sm-get-short-prefix ()
  (let ((shortname (org-entry-get-with-inheritance "SHORT"))
        (shortfilename (first (last (car (org-collect-keywords '("SHORT"))))))
        (trucname (truncate-string-to-width (or (car (last (org-get-outline-path))) "") 40 nil nil "...")))
    (cond (shortname shortname)
          (shortfilename shortfilename)
          (t trucname))))
#+END_SRC

**** Agenda skip function
#+BEGIN_SRC elisp
(defun sm-is-mixed-category ()
  (string= "mixed" (org-get-category)))
(defun sm-am-i-the-owner()
  (string= "swapnilsm" (org-entry-get-with-inheritance "OWNER")))
(defun sm-agenda-skip-function ()
  (let ((next-headline (save-excursion (org-entry-end-position))))
    (if (and (sm-is-mixed-category)
             (not (sm-am-i-the-owner)))
        next-headline
      nil)))
#+END_SRC
**** Get calendar agenda files
#+BEGIN_SRC elisp
(defun sm-get-calendar-agenda-files ()
  (list "~/work-sync/org-files/schedule/schedule.org"))
#+END_SRC
**** Get work agenda files
#+BEGIN_SRC elisp
(defun sm-get-work-agenda-files ()
  (list "~/work-sync/org-files/"))
#+END_SRC
**** Get personal agenda files
#+BEGIN_SRC elisp
(defun sm-get-personal-agenda-files ()
  (list "~/personal-sync/org-files/"))
#+END_SRC
**** Get org-roam agenda files
#+BEGIN_SRC elisp
(defun sm/org-roam-filter-by-tag (tag-name)
  (lambda (node)
    (member tag-name (org-roam-node-tags node))))

(defun sm/org-roam-list-notes-by-tag (tag-name)
  (mapcar #'org-roam-node-file
          (seq-filter
           (sm/org-roam-filter-by-tag tag-name)
           (org-roam-node-list))))

(defun sm/get-org-roam-agenda-files ()
  (sm/org-roam-list-notes-by-tag "Project"))

(defun sm/refresh-agenda-list ()
  (interactive)
  (setq org-agenda-files (delete-dups (append (sm/get-org-roam-agenda-files) (sm-get-personal-agenda-files) (sm-get-work-agenda-files))))
  (message "Refreshed org-agenda-files"))
#+END_SRC

**** Get org-roam projects
#+BEGIN_SRC elisp
(defun sm/org-roam-find-project ()
  (interactive)
  (org-roam-node-find
   nil
   nil
   (sm/org-roam-filter-by-tag "Project")))
#+END_SRC

*** Sensible defaults
#+BEGIN_SRC elisp
(after! org-agenda
  (map! :localleader
        :map org-agenda-mode-map
        "s" #'org-save-all-org-buffers)
  (setq org-agenda-skip-scheduled-if-deadline-is-shown t
        org-agenda-include-deadlines t
        org-agenda-show-all-dates nil
        org-agenda-compact-blocks t
        org-agenda-show-inherited-tags nil
        org-agenda-start-day nil
        org-agenda-breadcrumbs-separator " > "
        org-agenda-current-time-string "            "
        org-agenda-prefix-format
        '((agenda . " %i %?-12t %s %50(sm-get-short-prefix) > ")
          (todo . " %i %?-12t %11s %50b")
          (tags . " %i %?-12t % s %50(sm-get-short-prefix) > ")
          (search . " %i %?-12t % s %50(sm-get-short-prefix) > "))
        org-agenda-span 1))
#+END_SRC

*** Custom commands
***** By assignee
#+BEGIN_SRC elisp
(after! org-agenda
  (add-to-list 'org-agenda-custom-commands
               '("oo"  "By Owner"
                 ((agenda "" (
                              (org-agenda-skip-deadline-if-done nil)
                              (org-agenda-skip-scheduled-if-done nil)
                              (org-agenda-use-time-grid nil)
                              (org-super-agenda-groups
                               '(
                                 (:auto-property "OWNER")
                                 )
                               )))))))
#+END_SRC

***** My agenda
#+BEGIN_SRC elisp
(after! org-agenda
  (add-to-list 'org-agenda-custom-commands
               '("p"  "My agenda"
                 ((agenda "" (
                              (org-agenda-skip-function 'sm-agenda-skip-function)
                              (org-agenda-span 'day)
                              (org-agenda-clockreport-parameter-plist '(:narrow 80 :maxlevel 5 :fileskip0 t :link t :indent t :tcolumns 2))
                              (org-super-agenda-groups
                               '(
                                 (:name "Calendar"
                                  :time-grid t
                                  :date today
                                  :todo "TODAY"
                                  :scheduled today
                                  :order 4)
                                 (:name "Overdue - Not started"
                                  :and (:deadline past
                                        :not (:todo "STRT"))
                                  :order 1)
                                 (:name "Overdue - Started"
                                  :and (:deadline past
                                        :todo "STRT")
                                  :order 2)
                                 (:name "Due Today"
                                  :deadline today
                                  :order 3)
                                 (:name "Due Soon"
                                  :deadline future
                                  :order 5)
                                 (:name "Unplanned"
                                  :deadline nil
                                  :order 9)
                                 (:discard (:anything t))))))))))
                  ;; (todo "" ((org-agenda-overriding-header "")
                  ;;           (org-super-agenda-groups '(
                  ;;                                      (:name "Unplanned"
                  ;;                                       :deadline nil
                  ;;                                       :discard (:anything t))))))


#+END_SRC


** SUPER AGENDA
#+BEGIN_SRC elisp
(use-package! org-super-agenda
  :after org-agenda
  :init
  (setq org-super-agenda-groups '())
  (setq org-super-agenda-header-map (make-sparse-keymap))
  :config
  (org-super-agenda-mode)
  (message "org-super-agenda loaded"))
#+END_SRC

** AGENDA PROPERTY
#+BEGIN_SRC elisp
(use-package! org-agenda-property
  :after org-agenda
  :config
  (setq org-agenda-property-list '("NAME")
        org-agenda-property-position 'where-it-fits))
#+END_SRC
** POMODORO
#+BEGIN_SRC elisp
(use-package! org-pomodoro
  :after org-agenda
  :init
  (setq org-pomodoro-finished-sound "~/.doom.d/sounds/pomodoro-finished-sound.wav"))

#+END_SRC
** AUTO CLOCKOUT
#+BEGIN_SRC elisp
(after! org-clock
 (setq org-clock-auto-clockout-timer 1800)
 (org-clock-auto-clockout-insinuate))
#+END_SRC

** COPY LINK AT POINT
#+BEGIN_SRC elisp
(map! :localleader
      :map org-mode-map
      "ly" #'link-hint-copy-link-at-point
      )
#+END_SRC
** INSERT CURRENT ORG TIMER
#+BEGIN_SRC elisp
(defun sm-insert-current-org-timer ()
  (interactive)
  (save-excursion
    (if (org-in-regexp org-link-bracket-re 1)
        (let ((remove (list (match-beginning 0) (match-end 0))))
          (apply 'delete-region (list (match-beginning 0) (match-end 0)))))
    (progn (org-timer)
           (backward-delete-char 1))))
(after! org
  (map! :localleader
        :map org-mode-map
        :nv "i" nil
        (:prefix "i"
         :desc "Insert current timer" "t" #'sm-insert-current-org-timer)))
#+END_SRC

** INSERT CURRENT DATE
#+BEGIN_SRC elisp
(defun sm-current-date ()
  (format-time-string "%B %e, %Y"))

(defun sm-insert-current-date () (interactive)
       (insert (sm-current-date)))

(after! org
  (map! :leader
         (:prefix "i"
          :desc "Insert current date" "d" #'sm-insert-current-date)))
#+END_SRC

** INSERT UPDATE
#+BEGIN_SRC elisp
(defun sm/insert-update ()
  "Insert a new line just after the properties drawer of current heading starting with today's date."
  (interactive)
  (org-end-of-meta-data t)
  (newline)
  (previous-line)
  (insert "- [" (sm-current-date) "] ")
  (evil-append 1))
#+END_SRC

** GOOGLE CALENDAR
#+BEGIN_SRC elisp
;; (use-package! org-gcal
;;   :after org-agenda
;;   :init
;;   (setq org-gcal-client-id "client-id"
;;         org-gcal-client-secret "client-secret"
;;         org-gcal-file-alist '(
;;                               ("swapnilsm@google.com" . "~/schedule.org")
;;                               ))
;;   ;; (add-hook 'org-agenda-mode-hook (lambda () (org-gcal-fetch)))
;;   ;; (run-with-idle-timer 1800 t (lambda () (org-gcal-fetch)))
;;   )
#+END_SRC
** ORG PANDOC IMPORT
*** IMPORT
#+BEGIN_SRC elisp
(use-package! org-pandoc-import :after org)
#+END_SRC

** PRESENTATION
Set Org Reveal theme to "league"
#+BEGIN_SRC elisp
(after! org-re-reveal
  (setq org-re-reveal-theme "league"))
#+END_SRC

#+BEGIN_SRC elisp
(defun sm-org-present-start ()
  ;; Center the presentation and wrap lines
  (setq visual-fill-column-center-text t
        visual-fill-column-width 200)
  (visual-fill-column-mode 1)
  (visual-line-mode 1)
  (setq doom--line-number-style nil)
  (setq display-line-numbers nil))

(defun sm-org-present-end ()
  ;; Stop centering and wrapping lines
  (visual-fill-column-mode 0)
  (visual-line-mode 0)
  (setq doom--line-number-style 'relative)
  (setq display-line-numbers 'relative))

(defun sm-org-present-prepare-slide (buffer-name heading)
  ;; Show headlines only
  (org-overview)
  ;; Expand first headline
  (org-show-entry)
  ;; Fold the children
  (org-show-children))

;; Install visual-fill-column for centered text
(use-package! visual-fill-column
  :after org
  :config
  ;; Configure fill width
  (setq visual-fill-column-width 200
        visual-fill-column-center-text 1))

(use-package! org-present
  :after org
  :commands (org-present)
  :config
  ;; Override keys from evil-collections to sensible defaults
  (map! :map org-present-mode-keymap
        :n "j" #'evil-next-line
        :n "k" #'evil-previous-line
        :n "q" #'org-present-quit
        :n "zi" #'org-toggle-inline-images
        :n "zo" #'+org/open-fold)

  (map! :localleader
         :map org-mode-map
         :desc "present" "p" #'org-present)
  (add-hook! 'org-present-mode-hook 'sm-org-present-start)
  (add-hook! 'org-present-mode-quit-hook 'sm-org-present-end)
  (add-hook! 'org-present-after-navigate-functions 'sm-org-present-prepare-slide))
#+END_SRC

#+RESULTS:
: t

** SUPERSTAR
Set custom headline bullets
#+BEGIN_SRC elisp
(after! org-superstar
  :config
  (setq org-superstar-headline-bullets-list '("☯" "✸" "✿" "✜")))

#+END_SRC

* EXPAND REGION
#+BEGIN_SRC elisp
(map! :nv "C-," #'er/expand-region)
#+END_SRC

* BEACON
#+BEGIN_SRC elisp
(use-package! beacon
  :config (beacon-mode))
#+END_SRC

* DIMMER
#+BEGIN_SRC elisp
(use-package! dimmer
  :config
  (setq dimmer-fraction 0.50)
  (dimmer-mode)
  )
#+END_SRC

* AUTO REVERT
#+BEGIN_SRC elisp
(global-auto-revert-mode 1)
#+END_SRC
* HACKS
#+BEGIN_SRC elisp
(use-package! dired
  :init
  (when (string= system-type "darwin")
    (setq dired-use-ls-dired nil))
  :config
  (map! :map dired-mode-map :desc "Easy key for directory-up" :n "h" #'dired-up-directory)
  (map! :map dired-mode-map :desc "Easy key for directory-down/open" :n "l" #'dired-find-file))
#+END_SRC
* LEETCODE
#+BEGIN_SRC elisp
(use-package! leetcode
  :init
  (setq leetcode-save-solutions t)
  (setq leetcode-directory "~/leetcode")
  :commands (leetcode))
#+END_SRC
* PYTHON
#+BEGIN_SRC elisp
(after! python
  (setq python-shell-interpreter "python3")
  (setq python-shell-completion-native-enable nil))
#+END_SRC
* COMMAND LOG MODE
#+BEGIN_SRC elisp
(use-package! command-log-mode
  :commands (command-log-mode))
#+END_SRC
* PROTOBUF MODE
#+BEGIN_SRC elisp
;; (use-package! protobuf-mode)
#+END_SRC
* ORG ROAM
** ORG ROAM
#+BEGIN_SRC elisp
  (use-package! org-roam
    :after org-agenda
    :config
    (setq org-roam-completion-everywhere nil)
    (message "org-roam loaded")
    (sm/refresh-agenda-list)
    (map! :leader
          (:prefix "nr"
           :desc"Find project" "p" #'sm/org-roam-find-project))
    :custom
    (org-roam-directory "~/roam-files")
    (+org-roam-open-buffer-on-find-file 'nil)
    (org-roam-capture-templates
     '(("." "default" plain "%?"
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                           "#+TITLE: ${title}\n#+OPTIONS: toc:nil ^:nil\n#+FILETAGS: \n")
        :unnarrowed t)
       ("i" "interview notes" plain (file "~/roam-files/templates/interview-note-template.org")
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+TITLE: ${title}\n#+DATE: %U\n#+OPTIONS: toc:nil ^:nil\n#+STARTUP: overview\n#+FILETAGS: Interview\n")
        :unnarrowed t)
       ("d" "design" plain (file "~/roam-files/templates/design-template.org")
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+TITLE: ${title}\n")
        :unnarrowed t)
       ("p" "proposal" plain (file "~/roam-files/templates/proposal-template.org")
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+TITLE: ${title}\n")
        :unnarrowed t)
       ("P" "project" plain (file "~/roam-files/templates/project-note-template.org")
        :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+TITLE: ${title}\n#+SHORT: ${title}\n#+OPTIONS: toc:nil ^:nil\n#+STARTUP: show2levels\n#+FILETAGS: Project\n"))
       )
     )
    )
#+END_SRC

** ORG ROAM UI
#+BEGIN_SRC elisp
(use-package! websocket
    :after org-roam)

(use-package! org-roam-ui
    :after org-roam ;; or :after org
;;         normally we'd recommend hooking orui after org-roam, but since org-roam does not have
;;         a hookable mode anymore, you're advised to pick something yourself
;;         if you don't care about startup time, use
;;  :hook (after-init . org-roam-ui-mode)
    :config
    (setq org-roam-ui-sync-theme t
          org-roam-ui-follow t
          org-roam-ui-update-on-save t
          org-roam-ui-open-on-start t))
#+END_SRC
* UNDO TREE
#+BEGIN_SRC elisp
;; (use-package! undo-tree
;;   :hook (evil-local-mode . 'turn-on-undo-tree-mode))
#+END_SRC
* VTERM
Enable kill previous word with Meta-Backspace
#+BEGIN_SRC elisp
(map! :after vterm
      :map vterm-mode-map
      :ni "M-<backspace>" #'vterm-send-C-w)
#+END_SRC
* COMPANY
Introduce delay before dropdown is shown
#+BEGIN_SRC elisp
(after! company
  :config
  (setq company-idle-delay 1))
#+END_SRC
* REQUEST
#+BEGIN_SRC elisp
(use-package! request)
#+END_SRC
* GOOGLE
#+BEGIN_SRC elisp
(use-package! google)
#+END_SRC

** GOOGLE3

#+BEGIN_SRC elisp
(use-package! google3)
(use-package! google3-mode)
#+END_SRC

** FILE HANDLING
#+BEGIN_SRC elisp
(use-package! cs)

(use-package! google3-ffap
  :config
  (add-to-list 'ffap-alist (google3-ffap-alist-additions)))
(use-package! ffap-python
  :after (google3-ffap python)
  )
(use-package! rotate-among-files
  :config
  (setq google-rotate-directories '("public" "proto" "internal" "java" "javatests" "testdata")))
#+END_SRC

** REFERENCE, SEARCH, CORRECTION AND COMPLETION

#+BEGIN_SRC elisp
(use-package! ivy-cs
  :config
  (setq ivy-dynamic-exhibit-delay-ms 250)
  (setq ivy-cs--extra-args "--nostats --color=never")
  (setq cs-program "csearch"))
;; (use-package! google3-quickrun)
(use-package! google-flymake
  :config
  (remove-hook 'flymake-diagnostic-functions
               'flymake-proc-legacy-flymake))

(use-package! google3-eglot
  :after google
  :init
  (setq google3-eglot-ciderlsp-binary "~/bin/ciderlsp")
  (setq eglot-connect-timeout 30)
  :config
  (setq eglot-sync-connect 0)
  (google3-eglot-setup)
  (defun eglot--path-to-uri (path)
    "URIfy PATH."
    (url-hexify-string
     (concat "file://" (if (eq system-type 'windows-nt) "/")
           (string-remove-prefix "/Volumes" (file-truename path)))
     url-path-allowed-chars))
  (setq eldoc-message-commands (make-vector
                                eldoc-message-commands-table-size 0))
  (define-key eglot-mode-map [remap display-local-help] nil))


;; (cl-defun swapnilsm-connect-remote-ciderlsp (&optional (port 3845))
;;   "Launch eglot connected to a local port, which forwards to
;;   CiderLSP on a remote machine. See go/emacs-remote-ciderlsp for
;;   setup details."

;;   (interactive)

;;   ;; BEGIN: copied from //depot/google3/devtools/editors/emacs/google3-eglot.el

;;   ;; The legacy Flymake ‘proc’ backend won’t be useful in Google3 and will
;;   ;; interfere with Eglot.
;;   (setq-local flymake-proc-allowed-file-name-masks nil)
;;   ;; Company-clang conflicts with company completion from Eglot.
;;   ;; Disable it to avoid the issues.
;;   (setq-local company-backends
;;               (delq 'company-clang company-backends))
;;   ;; Make sure that ciderlsp specific capabilities won't trigger eglot to
;;   ;; emit errors.
;;   (setq-local eglot-strict-mode
;;               (remq 'disallow-non-standard-keys eglot-strict-mode))
;;   ;; `yas-minor-mode' is required for snippet based completion.
;;   (yas-minor-mode 1)

;;   ;; END: copied from //depot/google3/devtools/editors/emacs/google3-eglot.el

;;   ;; Eglot theoretically supports connecting to language servers over
;;   ;; TCP by just configuring `eglot-server-programs'. In practice this
;;   ;; doesn't work because `eglot--guess-contact' doesn't support it,
;;   ;; but is invoked by `eglot-ensure'.
;;   ;;
;;   ;; To work around this, we invoke eglot manually:
;;   (let* ((triplet (eglot--lookup-mode major-mode))
;;          (managed-modes (car triplet))
;;          (language-id (cadr triplet))
;;          (eglot-args (list managed-modes
;;                           (eglot--current-project)
;;                           'eglot-lsp-server
;;                           `("localhost" ,port)
;;                           language-id)))
;;     (eglot--when-live-buffer (current-buffer)
;;       (unless eglot--managed-mode
;;         (apply #'eglot--connect eglot-args)))))
;; (use-package! google-tricorder)
;; (use-package! google-findings)
#+END_SRC

** FIG

#+BEGIN_SRC elisp
(setq vc-hg-program "chg")
(setq fig--hg-executable "chg")
(setq fig-hg-executable "chg")
(use-package! vc-hgcmd
  :config (setq vc-handled-backends '(Hgcmd)))
(use-package! vc-defer
  :config
  (add-to-list 'vc-defer-backends 'Hg)
  (add-to-list 'vc-defer-backends 'Hgcmd)
  (add-to-list 'vc-defer-backends 'Fig)
  (vc-defer-mode))

#+END_SRC

** BUILD

#+BEGIN_SRC elisp
(use-package! google3-build
  :config
  (setq google3-build-target-method 'blaze))
(use-package! google3-build-mode
  :mode "\\BUILD$")
(use-package! google3-build-cleaner)
(use-package! google3-build-capf
 :config
 (google3-build-capf-enable-completions))
(use-package! iblaze-latest
  :after google3-build
  :config
  ;; (setq google3-build-command "blaze")
  (setq google3-build-command "iblaze -iblaze_nocitc_watch_all -iblaze_interrupt_on_change")
  (add-hook 'compilation-mode-hook 'iblaze-latest-mode)
  (setq compilation-scroll-output t))
;; (use-package! google3-build-mode-company
;;   :config
;;   (add-to-list 'company-backends 'company-capf))
#+END_SRC

** IMPORTS AND INCLUDES

#+BEGIN_SRC elisp
(use-package! google-imports)
(use-package! google-imports-iwyu)
(use-package! clang-include-fixer)
(use-package! google-cc-add-using)
(use-package! google-trailing-whitespace)
#+END_SRC

** CODING HELP AKA SNIPPETS

#+BEGIN_SRC elisp
;; (use-package! google-yasnippets
;;   :config
;;   (google-yasnippets-load))
;; (yas-global-mode 1)
;; (push "~/doom.emacs.d/snippets" yas-snippet-dirs)
#+END_SRC

** ENABLE GOOGLE3 AUTOGEN
#+BEGIN_SRC elisp
;; (use-package! google-codemaker
;;   :config (google-codemaker-auto-mode 1))
#+END_SRC

** LANGUAGE
*** PROTOBUF

#+BEGIN_SRC elisp
(use-package! protobuf-mode)
(use-package! protobuffer
  :config (setq protobuffer-format-before-save t))
#+END_SRC

*** CC

#+BEGIN_SRC elisp
(use-package! google-cc-extras)
(use-package! google-diformat)
#+END_SRC

*** DREMEL
#+BEGIN_SRC elisp
;; (use-package! sql-dremel)
#+END_SRC

*** FIG

#+BEGIN_SRC elisp
(use-package! fig
  :config
  (map! :map fig-status-mode-map
        "j" #'magit-section-forward
        "k" #'magit-section-backward))

;; go/emacs#support-for-git-with-magit
(defun sm/google3-early-exit (orig-fun &rest args)
  (if (string-prefix-p "/google/src/cloud/" (buffer-file-name))
      (progn (message "sm/google3-early-exit overrode.") nil)
    (apply orig-fun args)))

(after! magit
  (advice-add 'magit-toplevel :around #'sm/google3-early-exit)
  (advice-add 'magit-inside-worktree-p :around #'sm/google3-early-exit))
#+END_SRC

#+RESULTS:

*** JAVA

#+BEGIN_SRC elisp
(use-package! google-java-format)
(use-package! java-imports
  :config
  (setq java-imports-save-buffer-after-import-added nil)
  (add-hook! 'java-mode-hook 'java-imports-scan-file))
#+END_SRC

*** PYTHON

#+BEGIN_SRC elisp
(use-package! google-pyformat)
#+END_SRC

*** SOY

#+BEGIN_SRC elisp
(use-package! soy-mode)
#+END_SRC

*** SHX
#+BEGIN_SRC elisp
;; (use-package! shx)
#+END_SRC

*** SQL
#+begin_src elisp
;; (use-package! sql-dremel)
#+end_src

*** STYLE

#+BEGIN_SRC elisp
(setq frame-title-format
  '("" (:eval (save-match-data
                (if (string-match
                     "^/google/src/cloud/[^/]+/\\([^/]+\\)/"
                     default-directory)
                    (match-string 1 default-directory)
                  "%b")))))
#+END_SRC

** CUSTOM CODE
*** EDIFF

ediff press d to add both variants
#+BEGIN_SRC elisp
(defun ediff-copy-both-to-C ()
  (interactive)
  (ediff-copy-diff ediff-current-difference nil 'C nil
                   (concat
                    (ediff-get-region-contents ediff-current-difference 'A ediff-control-buffer)
                    (ediff-get-region-contents ediff-current-difference 'B ediff-control-buffer))))
(defun add-d-to-ediff-mode-map () (define-key ediff-mode-map "d" 'ediff-copy-both-to-C))
#+END_SRC
Don't let ediff open a new frame
#+BEGIN_SRC elisp
(setq ediff-window-setup-function 'ediff-setup-windows-plain)
#+END_SRC

** FORMATTING
#+BEGIN_SRC elisp
(set-formatter! 'google-diformat-clang-formatter #'google-diformat-clang-format-changed :modes '(c-mode c++-mode))
(set-formatter! 'google-diformat-python-formatter #'google-diformat-pyformat-changed :modes '((python-mode (not (eq major-mode 'google3-build-mode)))))
(set-formatter! 'google-diformat-java-formatter #'google-diformat-google-java-format-changed :modes '(java-mode))
(set-formatter! 'google-markdown-formatter #'google-mdformat :modes '(markdown-mode))
(setq +format-on-save-enabled-modes '(c-mode c++-mode python-mode typescript typescript-mode markdown-mode))
#+END_SRC

** EDIFF

#+BEGIN_SRC elisp
(use-package! google-ediff)
#+END_SRC

** LINKS & DOCUMENTATION

#+BEGIN_SRC elisp
(defun sm/org-dwim-at-point (fn &rest args)
  ;; First evaluate open-at-points function before running +org/dwim-at-point
  (unless (run-hook-with-args-until-success 'org-open-at-point-functions)
    (apply fn args)))
(use-package! gogolink
  :after google
  :hook ((org-mode . gogolink-mode)
         (org-agenda-mode . gogolink-mode))
  :config
  (map! :leader
        (:prefix "o"
         :desc "Open Google link in browser" "g" #'gogolink-goto-link-at-point))
  (advice-add '+org/dwim-at-point :around #'sm/org-dwim-at-point))
(use-package! browse-url)
(use-package! google-engdoc
  :init (google-engdoc-init))
#+END_SRC

** Buganizer

#+BEGIN_SRC elisp
(use-package! org-buganizer
  :after google
  :hook ((org-mode . org-buganizer-mode)))
#+END_SRC

** CUSTOM FUNCTIONS
*** Insert bug number from buganizer
#+BEGIN_SRC elisp
(defvar swapnilsm/insert-bug-cache nil)
(defun swapnilsm/clear-bug-cache ()
    "Clear bug cache"
  (interactive)
  (setq swapnilsm/insert-bug-cache nil))
(defun swapnilsm/insert-bug (&optional refresh)
  "Insert a bug number using Ivy and REFRESH cache if provided."
  (interactive "P")
  (let* ((buglist (or (and (not refresh) swapnilsm/insert-bug-cache)
                      (setq swapnilsm/insert-bug-cache
                            (cdr (process-lines "bugged" "search")))))
         (b (ivy-read "Bug: " buglist)))
    (insert (car (s-split-up-to "\s" b 1)))))
#+END_SRC
*** Safe shutdown
#+BEGIN_SRC elisp
(defun server-shutdown ()
  "Save buffers, Quit, and Shutdown (kill) server"
  (interactive)
  (save-some-buffers)
  (kill-emacs))
#+END_SRC
*** Fig - sync all
#+BEGIN_SRC elisp
(defun swapnilsm/fig-sync-all ()
  (interactive)
  (fig--hg-run-with-editor "sync" `(,@(fig--merge-tool-args) "--all")))
#+END_SRC
*** CS-Browse-Copy
#+BEGIN_SRC elisp
(defun swapnilsm/cs-browse-copy ()
  (interactive)
  (cs-browse 1))
#+END_SRC

*** Workspace build cleaner
#+BEGIN_SRC elisp
(defun swapnilsm/google3-build-cleaner-workspace ()
  (interactive)
  (google3-build-cleaner--run "-c=default"))
#+END_SRC

** HOOKS
#+BEGIN_SRC elisp
(add-hook! c++-mode
  (add-hook! 'before-save-hook :local :append #'google-clang-format-file nil :local))
(add-hook! typescript-mode
    (add-hook! 'before-save-hook :local :append #'google-diformat-clang-format-changed))
(add-hook! google3-mode 'subword-mode)
(add-hook! markdown-mode
  (lambda ()
    (unless (derived-mode-p 'fig-commit-mode)
      (add-hook 'before-save-hook #'google-mdformat-before-save nil t))))
(add-hook! python-mode
  (add-hook! 'before-save-hook :local :append
   (lambda ()
    (unless (eq major-mode 'google3-build-mode)
      (add-hook 'before-save-hook #'google-pyformat nil t)))))
;; (add-hook! 'java-mode-hook 'java-imports-scan-file)
;; (add-hook! java-mode
;;  (add-hook! 'before-save-hook :local :append #'google-java-format-buffer nil t))
;; (add-hook! eglot--managed-mode
;;   (add-hook! 'after-revert-hook :local :append #'eglot-reconnect))
;; (add-hook! 'after-revert-hook :append #'eglot-reconnect)
(add-hook! 'ediff-keymap-setup-hook :append #'add-d-to-ediff-mode-map)
(add-hook! 'after-init-hook :append #'global-company-mode)
(global-set-key (kbd "<f5>") #'company-complete)
#+END_SRC
** NECESSARY RATHER THAN USING DOOM AUTO-REVERT MODE TO ENABLE EGLOT-RECONNECT.
#+BEGIN_SRC elisp
(global-auto-revert-mode t)
#+END_SRC
** KEYMAP
#+BEGIN_SRC elisp
(map!
 (:leader
   :desc "" :nv "r" nil  ;; Unset reload bindings
   (:prefix "q"
     :desc "Kill emacs, save buffers" :nv "k" #'server-shutdown)
   (:prefix ("c" . "code")
     :desc "help at point"           :nv "h" #'eldoc-display-in-buffer
     :desc "format region or buffer" :nv "f" #'google3-format-region-or-buffer
     :desc "grab import"             :n  "g" #'google-imports-grab-import
     :desc "add grabbed imports"     :n  "G" #'google-imports-add-grabbed-imports
     :desc "add imports from prompt" :n  "I" #'google-imports-add-import-from-prompt
     :desc "import usingjava-imports" :n  "i" #'java-imports-add-import-dwim
     :desc "lint"                    :nv "l" #'google-lint
     :desc "list issues"             :n  "X" #'flymake-show-buffer-diagnostics
     :desc "fixits"                  :n  "x" #'eglot-code-actions
     ;; :desc "comment-or-un lines"     :nv "l" #'comment-or-uncomment-region
     :desc "rename symbol at point"  :nv "r" #'eglot-rename
     :desc "Flymake next error"      :n  "n" #'flymake-goto-next-error
     :desc "Flymake prev error"      :n  "N" #'flymake-goto-prev-error
     :desc "Expand region"           :nv "," #'er/expand-region
     :desc "Expand region"           :nv "<" #'er/contract-region)
   (:prefix ("d" . "docs")
     :desc "open engdoc"             :n "o" #'google-engdoc-current-file
     :desc "update freshdoc"         :n "u" #'google-engdoc-update-fresh)
   (:prefix "f"
     ;; :desc "code search"             :n "s" #'csearch
     :desc "ivyCS"                   :n "i" #'ivy-cs
     :desc "ivyCS Files"             :n "I" #'ivy-cs-files
     :desc "rotate-among-files"      :n "r" #'google-rotate-among-files)
     ;; :desc "create cc Files"         :n "C" #'google-cc-extras-create-files)
   (:prefix ("v" . "fig")
    ;; a Adding and removing files
    ;; b Bookmarking
    ;; c Committing
    ;; d Diffing and getting comments
    ;; f Fixing
    ;; F Pulling, syncing
    ;; P Pushing
    ;; r Rebasing
    ;; R Mailing
    ;; t Tagging
    ;; V Reverting
    ;; ! Running
    ;; z Shelving
     :desc "fig status"              :n "s" #'fig-status
     :desc "fig fix"                 :n "f" #'fig-fix
     :desc "sync all"                :n "p" #'swapnilsm/fig-sync-all
     :desc "committing"              :n "c" #'fig-commit-popup
     :desc "pushing"                 :n "P" #'fig-push-popup
     :desc "rebasing"                :n "r" #'fig-rebase-popup
     :desc "mailing"                 :n "R" #'fig-mail-popup
     :desc "reverting"               :n "V" #'fig-revert-popup
     :desc "annotate blame"          :n "b" #'g4-annotate)
   (:prefix ("r" . "run")
     :desc "build-cleaner workspace" :n "c" #'swapnilsm/google3-build-cleaner-workspace
     :desc "build-cleaner"           :n "C" #'google3-build-cleaner-autogen
     :desc "blaze build"             :n "B" #'google3-build-current-build-rule
     :desc "blaze build"             :n "b" #'google3-build
     :desc "blaze test"              :n "t" #'google3-test
     :desc "iwyu"                    :n "I" #'google-imports-iwyu
     :desc "build Fix"               :n "f" #'google3-build-fix)
   (:prefix "s"
    :desc "Search in CodeSearch"     :n "c" #'ivy-cs)
   (:prefix "i"
    :desc "insert bug ID"            :n "b" #'swapnilsm/insert-bug)
   ))

(map! "M-f" #'swiper)
#+END_SRC

** HACKS
#+BEGIN_SRC elisp
;; (load "/usr/share/google-emacs/site-lisp/emacs-google-config/third_party/elisp/flymake/flymake.el")
;; (defun project-root (p)  (car (project-roots p)))
#+END_SRC

** SPEED UP FILE OPENS
#+BEGIN_SRC elisp
(remove-hook 'find-file-hook 'p4-update-status)
(remove-hook 'find-file-hook 'google-load-p4-if-useful-hook)
#+END_SRC

** EXPAND REGION
#+BEGIN_SRC elisp
(map! :nv "C-," #'er/expand-region)
#+END_SRC

** PROJECTILE
#+BEGIN_SRC elisp
(use-package! projectile
  :hook
  (after-init . projectile-mode)
  :init
  (setq projectile-known-projects-file "~/known-projects-file.eld"
        projectile-track-known-projects-automatically nil)
  :config
  ;; Do not cleanup non-existing projects due to expired gcert
  (remove-hook! 'kill-emacs-hook #'doom-cleanup-project-cache-h)
  (add-to-list 'projectile-project-root-files-bottom-up "OWNERS")
  (setq projectile-hg-command "find . -type f | cut -c3- | tr '\\n' '\\0'"))
#+END_SRC

** DATE/TIME/CALENDAR
*** Date
#+BEGIN_SRC elisp
(defun swapnilsm/insert-current-date ()
  (interactive)
  (insert (calendar-date-string (calendar-current-date) nil 1)))
(map! :leader
      (:prefix "i"
       :desc "Insert current date" :ni "d" #'swapnilsm/insert-current-date))
#+END_SRC
*** Time/Timer
#+BEGIN_SRC elisp
(map! :leader
      (:prefix "i"
       :desc "Insert time elapsed(Timer)" :nvi "t"  #'org-timer))
#+END_SRC

** Test
#+BEGIN_SRC elisp
;; built-in `project' on 26+
(setq doom-modeline-project-detection 'project)
;; or `find-in-project' if it's installed
(setq doom-modeline-project-detection 'ffip)
(setq find-file-visit-truename nil)
#+END_SRC
